### ISSUE TITLE
Istio-Pilot not validating ingress yaml

### ISSUE THREAD

**Issue by meinenec** [istio/issues#137]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.3.0
GitRevision: 24ec6a3ac3a1d592d1873d2d8198278a849b8301
GitBranch: ad6c09778ae6218b51c91ed53aafc7f9e13796b3
User: root@24c944bda24b
GolangVersion: go1.8

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
No

**What happened**:
Incorrectly formatted ingress yaml file was allowed to run resulting in the istio-pilot discovery container falling into a crashLoopBackoff and giving logs:
```
ERROR: logging before flag.Parse: I1218 16:51:57.537610       1 discovery.go:339] Cleared discovery service cache
ERROR: logging before flag.Parse: I1218 16:53:10.537547       1 controller.go:93] ingress event add for default/simple-ingress
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1318fc1]

goroutine 117 [running]:
istio.io/istio/pilot/adapter/config/ingress.convertIngress(0x0, 0x0, 0x0, 0x0, 0xc4204d8700, 0xe, 0x0, 0x0, 0xc4204d8710, 0x7, ...)
	pilot/adapter/config/ingress/conversion.go:54 +0x461
istio.io/istio/pilot/adapter/config/ingress.(*controller).RegisterEventHandler.func1(0x1752d00, 0xc4203371e0, 0x0, 0x0, 0x0)
	pilot/adapter/config/ingress/controller.go:117 +0x119
istio.io/istio/pilot/platform/kube.(*ChainHandler).Apply(0xc420407fc0, 0x1752d00, 0xc4203371e0, 0x0, 0xc4202fe720, 0x1)
	pilot/platform/kube/queue.go:120 +0x81
istio.io/istio/pilot/platform/kube.(*ChainHandler).Apply-fm(0x1752d00, 0xc4203371e0, 0x0, 0xc4202f3c20, 0x0)
	pilot/adapter/config/crd/controller.go:119 +0x48
istio.io/istio/pilot/platform/kube.(*queueImpl).Run(0xc4202a2ff0, 0xc42015e180)
	pilot/platform/kube/queue.go:100 +0x18d
created by istio.io/istio/pilot/adapter/config/ingress.(*controller).Run
	pilot/adapter/config/ingress/controller.go:131 +0x54
rpc error: code = Unknown desc = Error: No such container: 41c30ad9efb0c13c889b35f09f18754a9b2d439de14b5e2b477750642873be56%
```

**What you expected to happen:**
Istio pilot would not crash.

**How to reproduce it:**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: gohan.com
  - http:
      paths:
      - path: /status/.*
        backend:
          serviceName: httpbin
          servicePort: 8000
```

**Comment by jmuk** [comment]
@ayj can you take a look?

**Comment by jmuk** [comment]
I've heard @ayj is off today; first, please remove that config with `kubectl`, like `kubectl delete simple-ingress`, then fix the config and then recreate it. I think the problem is parsing incorrect data, correctly it would be:
```diff
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: simple-ingress
   annotations:
     kubernetes.io/ingress.class: istio
 spec:
   rules:
   - host: gohan.target.com
-  - http:
+    http:
       paths:
       - path: /status/.*
         backend:
           serviceName: httpbin
           servicePort: 8000
```

Apparently crash-loop is a bug. Filed https://github.com/istio/istio/issues/2226 too.

**Comment by meinenec** [comment]
@jmuk I was able to resolve the problem previously following those steps. I just wanted to report the bug. I believe https://github.com/istio/istio/issues/2226 achieves this.

Thank you!
