### ISSUE TITLE
istio-proxy-cfg.py backtraces if there are no labels

### ISSUE THREAD

**Issue by esnible** [istio/issues#199]
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
I am using https://github.com/istio/istio/blob/master/bin/istio-proxy-cfg.py from HEAD.  Not using _istioctl_.  _kubectl_ 1.7 against a 1.8 server.

**Is Istio Auth enabled or not ?**
Enabled

**What happened**:
```
python istio-proxy-cfg.py  wandering-seahorse-customerdb-couchdb-598fb75855-f7p27
Traceback (most recent call last):
  File "istio-proxy-cfg.py", line 226, in <module>
    sys.exit(main(args))
  File "istio-proxy-cfg.py", line 187, in main
    pod = searchpod(pod_info(), args.podname)
  File "istio-proxy-cfg.py", line 163, in pod_info
    i['status']['podIP'], i['metadata']['labels']) for i in o['items']}
  File "istio-proxy-cfg.py", line 163, in <dictcomp>
    i['status']['podIP'], i['metadata']['labels']) for i in o['items']}
KeyError: 'labels'
```

**What you expected to happen:**
I expected it to say "Wrote  wandering-seahorse-customerdb-couchdb-598fb75855-f7p27_proxy_xds.yaml"

**How to reproduce it:**
I am not sure.  I have a fix for it though.  In _istio-proxy-cfg.py_ change line 163 to have a default for ['labels'], like this:

```
                i['status']['podIP'], i['metadata'].get('labels', {})) for i in o['items']}
```

**Comment by mandarjog** [comment]
Hi Ed thanks for the issue.
Since you have a fix can you send a PR?

**Comment by louiscryan** [comment]
Closing now that PR is committed.
