### ISSUE TITLE
All bookinfo reviews pods have CrashLoopBackOff state

### ISSUE THREAD

**Issue by Vikash082** [istio/issues#283]
**Is this a BUG or FEATURE REQUEST?:**  BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.7.1
kubectl version: v1.10.0
CentOS Linux release 7.4.1708
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
```
kubectl apply -f install/kubernetes/istio-auth.yaml
```

**What happened**:
All the three reviews-v1-xxxx pods are crashing. Used kubectl logs <pod> to get the below log.
```
CWWKE0005E: The runtime environment could not be launched.
CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:524)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:211)
        at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:244)
        at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:119)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
Caused by: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelUtils.cleanDirectory(KernelUtils.java:213)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.clearServerStateDir(KernelBootstrap.java:226)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:102)
        ... 4 more
```

**What you expected to happen:**
All the three review pods should run.

**How to reproduce it:**
```
kubectl apply -f samples/bookinfo/kube/bookinfo.yaml
```

**Feature Request:**
N

**Describe the feature:**

**Comment by ayj** [comment]
Can you provide more information on your test environment / cluster?

cc @linsun @frankbu - any ideas why the bookinfo review app might be crashing?

**Comment by Vikash082** [comment]
I have 2 physical nodes, one master and one worker. These two machines have 57G free memory and enough disk space. Both the nodes are Centos systems.

Pod info:
```
$ kubectl get pods --all-namespaces
NAMESPACE      NAME                                      READY     STATUS             RESTARTS   AGE
default        details-v1-7b97668445-4s9vl               1/1       Running            0          3h
default        productpage-v1-7bbdd59459-27ndc           1/1       Running            0          3h
default        ratings-v1-76dc7f6b9-qm5s4                1/1       Running            0          3h
default        reviews-v1-64545d97b4-4n246               0/1       CrashLoopBackOff   46         3h
default        reviews-v2-8cb9489c6-c9bdq                0/1       CrashLoopBackOff   46         3h
default        reviews-v3-6bc884b456-pw4t8               0/1       CrashLoopBackOff   46         3h
istio-system   istio-ca-75fb7dc8d5-xdtcc                 1/1       Running            0          6h
istio-system   istio-ingress-8546966f58-4c9r8            1/1       Running            0          6h
istio-system   istio-mixer-566f68f5d6-zkqg5              3/3       Running            0          6h
istio-system   istio-pilot-fd8fb6957-w6m4w               2/2       Running            0          6h
istio-system   istio-sidecar-injector-844b9d4f86-mgbjl   1/1       Running            0          3h
kube-system    etcd-os-ctrl-14                           1/1       Running            1          6d
kube-system    kube-apiserver-os-ctrl-14                 1/1       Running            1          6d
kube-system    kube-controller-manager-os-ctrl-14        1/1       Running            1          6d
kube-system    kube-dns-86f4d74b45-wwvwc                 3/3       Running            24         6d
kube-system    kube-flannel-ds-qtpz7                     1/1       Running            0          6d
kube-system    kube-flannel-ds-srrgc                     1/1       Running            1          6d
kube-system    kube-proxy-5pnmz                          1/1       Running            1          6d
kube-system    kube-proxy-p98rp                          1/1       Running            0          6d
kube-system    kube-scheduler-os-ctrl-14                 1/1       Running            1          6d
```
cluster-info:
```
 kubectl cluster-info
Kubernetes master is running at https://192.168.xx.yy:6443
KubeDNS is running at https://192.168.xx.yy:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
Let me know, if more information is needed.

**Comment by hexingmin01** [comment]
I have the same problems,and wait for to be solved


CWWKE0005E: The runtime environment could not be launched.
CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:510)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:206)
        at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:245)
        at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:120)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:60)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:36)
Caused by: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelUtils.cleanDirectory(KernelUtils.java:203)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.clearServerStateDir(KernelBootstrap.java:221)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:100)
